### ISSUE TITLE
Feature: 'report mode' output with configurable cycles

### ISSUE THREAD

**Issue by terackspace** [CharlesMcKinnis/StuckProcCoreScreening#1]
The script uses ANSI and rewrites the screen repeatedly, leaving no good option for having a finalized report that can be cut & pasted for various needs. I'd like the ability to run in "report mode" with a given number of cycles.
- instead of drawing all output to the screen, it simply displays an iteration counter of the number of cycles as it's running to provide basic feedback.
- when complete it displays a single table of the collected observations including a legend of number of iterations and the time consumed (so that multiple runs can be saved side by side for comparison)

Side note: when pressing Ctrl+C in interactive mode it leaves the screen "dirty" with lots of overwritten garbage. The above feature request could also be used for Ctrl+C -- as it exits, it displays the same accumulated data as report mode (clear screen, print final output).

**Comment by CharlesMcKinnis** [comment]
Thank you for the ideas :)

Let me give some thought about how to implement it. The cursor already "rests" at the bottom between cycles, so anything that exits cleanly should leave the prompt below it. These are the items I am thinking about:
- A report mode that runs for an argument specified time, then stops. "--report [30]" in seconds, defaulting to 30 seconds if omitted.
- Catch Ctrl+C, print the screen and exit to the prompt below the output; When the screen is full of garbage, it was interrupted during a print cycle. Since that happens very often, it is likely to be the case.
- Or simply catch the Ctrl+C and break the loop so it finishes the output.

**Comment by CharlesMcKinnis** [comment]
I have added command line switches to provide the functionality you requested. Please let me know if there is anything additional I may assist you with, Charles

```
$ ./StuckProcCoreScreening.py -h
usage: StuckProcCoreScreening.py [-h] [-r RUNTIME] [-s] [-b] [--plaintext]

optional arguments:
  -h, --help            show this help message and exit
  -r RUNTIME, --runtime RUNTIME
                        Maximum number of seconds to watch the CPUs before
                        ending
  -s, --silent          No output, return code of 0 if CPUs are clear, and
                        non-zero if the CPUs do not hit max within the runtime
                        specified. Default 30 seconds, use --runtime to
                        specify the duration.
  -b, --batch           Run for a time, then output results. Default 30
                        seconds, use --runtime to specify the duration.
  --plaintext           ANSI control characters are omitted for colors and
                        screen clear/home.
```
